config/routes.rb
Rails.application.routes.draw do
  get 'top/main'
  post 'top/login'
  root 'top#main'
  get 'top/logout'
  
  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  allow_browser versions: :modern
  
  def L4
    session[:c] ||= 0
    session[:c] = session[:c].to_i + 1
    render plain: session[:c]
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    if session[:login_uid] != nil
      render "main"
    else
      render "login"
    end
  end
  
  def login
    if User.find_by(uid: params[:uid], pass: params[:pass]) != nil
      logger.debug "ログイン成功"
      session[:login_uid] = params[:uid]
      redirect_to top_main_path
    else
      render "error", status: 442
    end
  end
  
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cs" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/error.html.erb
<h1>ログイン失敗！</h1>
<%= link_to "戻る", :back %>

app/views/top/login.html.erb
<%= form_with url: top_login_path, method: :post, local: true do |f| %>
  <%= f.label :uid, 'ユーザーID' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'パスワード' %>
  <%= f.password_field :pass %>
  <%= f.submit 'ログイン' %>
<% end %>

app/views/top/main.html.erb
<h1>ログイン中です。</h1>
<%= link_to 'ログアウト', top_logout_path %>